### PR TITLE
Maartjes branch

### PR DESCRIPTION
**Pull request by maartjepontier**
Added some features

### CODE REVIEW

**Review by DaanVerheijen — COMMENTED** [review]
Looks good :) approved!

**Review by DaanVerheijen — APPROVED** [review]
looks good :)

**Comment by DaanVerheijen** [comment]
curly leaves wont work, please make them square.
please name the water retentionfeature "bucket"

**Comment by bkarpati** [comment]
Thanks for participating in the Git workshop. I'm going to close this PR for now and also delete the remote branch.
Please stay tuned for the follow-up.

**Pull request closed without merging**
